### PR TITLE
Add Don P.M.

### PR DESCRIPTION
**Pull request by raddevon**

### CODE REVIEW

**Review by Delta456 — COMMENTED** [review]
I think it's better to have a separate category called Tutorials/Blogs.

cc @isabelroses @wissam

**Comment by isabelroses** [comment]
> I think it's better to have a separate category called Tutorials/Blogs.

I agree. And I think this was also the consensus on the discord server too.

**Comment by raddevon** [comment]
Thanks for the feedback! I pushed another commit to move it to a new "Tutorials" category under "Other."

**Comment by wissam** [comment]
Thank you

**Pull request merged**
